
import React, { useState } from 'react';
import { GithubService, GithubFile } from '../services/githubService';

const DeploymentPanel: React.FC = () => {
  const [repoName, setRepoName] = useState('YOUR_USERNAME/YOUR_REPO_NAME');
  const [token, setToken] = useState('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');
  const [status, setStatus] = useState<'IDLE' | 'PUSHING' | 'SUCCESS' | 'ERROR'>('IDLE');
  const [progress, setProgress] = useState({ current: 0, total: 0, file: '' });

  // List of files to be pushed to the repository
  // In a real app, this would be generated by a build script or a file map
  const getProjectFiles = (): GithubFile[] => {
    // Note: We are using placeholders for the actual content. 
    // In this specific environment, we are pushing the "live" state of the files.
    return [
      { path: 'package.json', content: localStorage.getItem('src_package.json') || '' },
      { path: 'vite.config.ts', content: localStorage.getItem('src_vite.config.ts') || '' },
      { path: 'tsconfig.json', content: localStorage.getItem('src_tsconfig.json') || '' },
      { path: 'index.html', content: document.documentElement.outerHTML },
      { path: 'metadata.json', content: '{"name": "Digital Riyal Network Treasury wallet"}' }
    ];
  };

  const handleDeploy = async () => {
    if (!repoName.includes('/')) return alert("Enter Repo Name as 'username/repository'");
    
    setStatus('PUSHING');
    const github = new GithubService(token, repoName);
    
    // We get the current content of relevant files to push
    // For this demo, we'll notify the user we're preparing their specific build
    const files = getProjectFiles();
    
    const success = await github.pushProject(files, (file, current, total) => {
      setProgress({ file, current, total });
    });

    if (success) {
      setStatus('SUCCESS');
    } else {
      setStatus('ERROR');
      alert("Deployment failed. Please check your Token permissions or Repo Name.");
    }
  };

  return (
    <div className="max-w-4xl mx-auto animate-in fade-in slide-in-from-bottom-4 duration-500">
      <div className="glass rounded-3xl overflow-hidden">
        <div className="p-8 border-b border-slate-800 bg-slate-900/50 flex justify-between items-center">
          <div>
            <h2 className="text-2xl font-bold mb-2">Cloud Deployment Hub</h2>
            <p className="text-slate-400">Push your Digital Riyal Treasury code directly to GitHub.</p>
          </div>
          <div className="w-12 h-12 bg-purple-600/20 rounded-2xl flex items-center justify-center text-purple-400">
            <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M7 16a4 4 0 01-.88-7.903A5 5 0 1115.9 6L16 6a5 5 0 011 9.9M15 13l-3-3m0 0l-3 3m3-3v12"/></svg>
          </div>
        </div>

        <div className="p-8 space-y-8">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div className="space-y-2">
              <label className="text-sm font-semibold text-slate-400 px-1">GitHub Repository (owner/repo)</label>
              <input 
                type="text" 
                value={repoName}
                onChange={(e) => setRepoName(e.target.value)}
                placeholder="e.g. digitalriyal/treasury-wallet"
                className="w-full bg-slate-950 border border-slate-800 rounded-xl p-4 text-sm focus:ring-2 focus:ring-purple-500 outline-none transition-all"
              />
            </div>
            <div className="space-y-2">
              <label className="text-sm font-semibold text-slate-400 px-1">Access Token</label>
              <input 
                type="password" 
                value={token}
                onChange={(e) => setToken(e.target.value)}
                className="w-full bg-slate-950 border border-slate-800 rounded-xl p-4 text-sm focus:ring-2 focus:ring-purple-500 outline-none transition-all"
              />
            </div>
          </div>

          {status === 'PUSHING' && (
            <div className="space-y-4 animate-in fade-in slide-in-from-top-2">
              <div className="flex justify-between text-xs font-bold uppercase tracking-widest text-slate-500">
                <span>Uploading: {progress.file}</span>
                <span>{Math.round((progress.current / progress.total) * 100)}%</span>
              </div>
              <div className="w-full bg-slate-900 h-2 rounded-full overflow-hidden">
                <div 
                  className="bg-purple-500 h-full transition-all duration-300"
                  style={{ width: `${(progress.current / progress.total) * 100}%` }}
                ></div>
              </div>
            </div>
          )}

          {status === 'SUCCESS' && (
            <div className="bg-emerald-500/10 border border-emerald-500/20 rounded-2xl p-6 flex gap-4 items-center animate-in zoom-in-95">
              <div className="w-12 h-12 bg-emerald-500 rounded-full flex items-center justify-center text-white shrink-0">
                <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="3" d="M5 13l4 4L19 7"/></svg>
              </div>
              <div>
                <p className="font-bold text-emerald-400">Deployment Successful!</p>
                <p className="text-sm text-slate-400">Your files are now live on GitHub. You can now connect this repo to Vercel.</p>
                <a 
                  href={`https://github.com/${repoName}`} 
                  target="_blank" 
                  rel="noreferrer"
                  className="text-xs text-purple-400 hover:underline mt-1 inline-block font-bold"
                >
                  View Repository on GitHub →
                </a>
              </div>
            </div>
          )}

          <div className="bg-slate-900/50 p-6 rounded-2xl border border-slate-800 flex gap-4">
            <div className="text-purple-400 pt-1">
              <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"/></svg>
            </div>
            <div className="text-sm text-slate-400 leading-relaxed">
              <p className="font-bold text-slate-200 mb-1">Non-Developer Instructions</p>
              1. Enter your GitHub **username** and **repository name** above.<br/>
              2. Click the button below to upload all project files automatically.<br/>
              3. Once complete, go to **Vercel.com** to launch your website globally.
            </div>
          </div>

          <button 
            onClick={handleDeploy}
            disabled={status === 'PUSHING'}
            className="w-full py-5 bg-gradient-to-r from-purple-600 to-indigo-600 hover:from-purple-500 hover:to-indigo-500 text-white font-bold rounded-2xl shadow-2xl shadow-purple-600/20 flex items-center justify-center gap-3 transition-all disabled:opacity-50"
          >
            {status === 'PUSHING' ? (
              <>
                <svg className="animate-spin h-5 w-5 text-white" fill="none" viewBox="0 0 24 24"><circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle><path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path></svg>
                Transmitting Files...
              </>
            ) : (
              <>
                <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4"/></svg>
                Push to GitHub Repository
              </>
            )}
          </button>
        </div>
      </div>
    </div>
  );
};

export default DeploymentPanel;
